### ISSUE TITLE
Using realizeNTF() function with a non-null STF parameter

### ISSUE THREAD

**Issue by g-c-98** [Y-F-Acoustics/python-deltasigma#36]
When you try to call the "realizeNTF()" function while also passing an STF as a parameter, you get an IndexError:

Traceback (most recent call last):
_File "...", line 565, in
struct = ds.realizeNTF(ntf, form, stf)
File "...", line 367, in realizeNTF
bi[i] = 1
IndexError: index 1 is out of bounds for axis 0 with size 1_

Code for testing (any STF can be used, same error will appear):

```
import numpy as np
from scipy import signal as sp_sig
import deltasigma as ds

# "realizeNTF()" tests - with STF
order = 3
osr = 32
forms = np.array( ['CRFB', 'CRFF', 'CIFB', 'CIFF', 'CRFBD', 'CRFFD'] )
form = forms[0]

ntf = ds.synthesizeNTF(order, osr, 1)
print(f"ntf = ds.synthesizeNTF({order}, {osr}, 1) = \n", ntf), print()

stf = (np.array([0.0, 0.0, 0.0]), ntf[1], 1)
print(f"stf = \n", stf), print()

struct = ds.realizeNTF(ntf, form, stf)
print(f"struct = ds.realizeNTF(ntf, {form}, stf) = \n", struct), print()
```

**Comment by g-c-98** [comment]
The code inside "detltasigma\_realizeNTF.py", at line 367, probably meant to access a single element inside the row-vector of zeros created at line 366. Instead, the code "bi[i]" accesses the entire row with index "i" (and, since there is only one row, at the second loop of the "for", it tries to access row 1, which does not exist), instead of only accessing element "i" of row-vector "bi"
